<?php declare(strict_types=1);

/**
 * My API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface DefaultApiInterface {


    /**
     * Operation usersPost
     *
     * ユーザー作成
     * @param \OpenAPI\Server\Model\UserCreate $userCreate
     * @return \OpenAPI\Server\Model\User
     */
    public function usersPost(
            \OpenAPI\Server\Model\UserCreate $userCreate,
    ):
        \OpenAPI\Server\Model\User
    ;

}
